### ISSUE TITLE
Missing Reference

### ISSUE THREAD

**Issue by wutaiqiang** [princeton-nlp/LLM-Shearing#1]
Nice work!

Targeted structured pruning seems to be similar to WID (https://arxiv.org/abs/2305.09098).

Please consider discussing it in the related work section.

Thanks!

**Comment by xiamengzhou** [comment]
Thanks for the pointer -- The work you mentioned is very relevant and we will include it in our next revision!

**Comment by wutaiqiang** [comment]
One kind reminder to add our paper as a reference. I appreciate your time. Thanks!

**Comment by wutaiqiang** [comment]
@xiamengzhou

**Comment by xiamengzhou** [comment]
Hi, we are still in the process of preparing for camera ready. Will update the arxiv version soon!

**Comment by wutaiqiang** [comment]
Really appreciate it, thanks~
