### ISSUE TITLE
Can Sheared-LLaMA beat OpenLLaMA v2 significantly with the same amount of compute ?

### ISSUE THREAD

**Issue by lxww302** [princeton-nlp/LLM-Shearing#10]
<img width="517" alt="image" src="https://github.com/princeton-nlp/LLM-Shearing/assets/68112258/4c9135b4-51a8-45a6-9ffb-f8cd4cd08bc9">

We can see from the picture that  Sheared-LLaMA is on par with OpenLLaMA v2 with 1/32 compute, which is quite impressive. But from my experience, knowledge distillation and pruning is very data efficient indeed, but can not surpass pre-training from scatch significantly due to the size limit of the target model. I wonder if you train Sheared-LLaMA-2.7B longer, is it possible to surpass Open-LLaMA-3B-v2 by 4~5% on average downstream performance ?

**Comment by xiamengzhou** [comment]
Hello! We believe that Sheared-LLaMA has the potential to significantly improve its performance as the number of training tokens increases, as indicated by the observed trend. We weren't able to put in more compute because of computational constraints on our end.

**Comment by lucasjinreal** [comment]
Try mistral7b to see when we can have a 3d compareable with 7b model
