### ISSUE TITLE
Dynamic Batch Loading v.s. Domain Reweighting

### ISSUE THREAD

**Issue by lxww302** [princeton-nlp/LLM-Shearing#11]
<img width="1029" alt="image" src="https://github.com/princeton-nlp/LLM-Shearing/assets/68112258/f705497b-aca9-447d-ba00-6f426238724e">

we can see from Table 3 that dynamic batch loading results in down-sampling CC & Github and up-sampling Book & C4. I wonder if   I re-sample the pretraining data according to this recipe ahead-of-time, and do pruning and continue-training on the re-sampled data directly, will it reach the same performance ?

**Comment by xiamengzhou** [comment]
This is certainly an interesting question! We didn't conduct experiments to verify this hypothesis, but my guess is that the results shall be very similar to dynamic batch loading.
