### ISSUE TITLE
Small typo on Table 2

### ISSUE THREAD

**Issue by lxww302** [princeton-nlp/LLM-Shearing#12]
<img width="1017" alt="image" src="https://github.com/princeton-nlp/LLM-Shearing/assets/68112258/f3052e7e-d09b-4680-a63b-225872227307">

Pythia-1.4B seems to be better than OPT-1.3B and Sheared-LLaMA-1.3B on LogiQA. :)

**Comment by danqi** [comment]
Thanks! We will update the draft.
