### ISSUE TITLE
Sample.py error when sampling stackexchage

### ISSUE THREAD

**Issue by Longyichen** [princeton-nlp/LLM-Shearing#14]
SLURM_ARRAY_TASK_ID=5 python sample.py --target_dir mds_redpajama --tokenized_dir hadoop/tokenized_redpajama An error will occur. The reason is that stackexchage only has one file, while sample.py requires multiple files to be split
```Split: stackexchange
> /root/personal-code/LLM-Shearing/llmshearing/data/sample.py(69)<module>()
-> folder_eval_target = args.eval_seq
(Pdb) c
Traceback (most recent call last):
  File "/root/personal-code/LLM-Shearing/llmshearing/data/sample.py", line 70, in <module>
    num_sample_each_file = max(1, folder_eval_target // len(selected) + 1)
ZeroDivisionError: integer division or modulo by zero```

**Comment by xiamengzhou** [comment]
@gaotianyu1350 Could you help with this?

**Comment by gaotianyu1350** [comment]
@Longyichen Hi, can you make sure there are files in the designated folder? It seems that the program did not detect any

**Comment by Longyichen** [comment]
@gaotianyu1350 yes,
```
for folder in target_folders:
    print("Split: %s" % folder)
    random.shuffle(folder_to_files[folder])
    # Use the first half of files as evaluation
    selected = folder_to_files[folder][:len(folder_to_files[folder]) // 2]
    # The left will be used for training later
    folder_to_files[folder] = folder_to_files[folder][len(folder_to_files[folder]) // 2:]

    # Check if the files exist    
    selected_verified = []
    for fname in selected:
        if os.path.exists(fname):
            selected_verified.append(fname)
    selected = selected_verified
    if len(selected) == 0:
        import pdb; pdb.set_trace()
```
in code, folder_to_files[folder] has only one file, then selected = folder_to_files[folder][:len(folder_to_files[folder]) // 2] might be zero
i use pdb, result as:
(Pdb)  folder_to_files[folder]
['hadoop/tokenized_redpajama/stackexchange/part-00000.npy']
(Pdb) len(folder_to_files[folder])
1
(Pdb) folder_to_files[folder][:len(folder_to_files[folder]) // 2]
[]
(Pdb) len(folder_to_files[folder]) // 2
0
(Pdb) selected = folder_to_files[folder][:len(folder_to_files[folder]) // 2]
(Pdb) selected
[]
In your readme, it also says "that means you need to have at least two files for each domain". However, in the public redjama data set, the stack data only has one file. I also tried sampling through segmentation, but I encountered some problems later.

**Comment by Longyichen** [comment]
After I used the following script to split the data, it ran normally.
But please pay attention to modify the corresponding jsonl_all.txt

```
import numpy as np

# 读取文件
data = np.load('hadoop/tokenized_redpajama/stackexchange_copy/part-00000.npy')

# 计算每个部分的大小
split_size = len(data) // 10

# 分割并保存
for i in range(10):
    start_index = i * split_size
    # 最后一部分取剩余的所有元素
    end_index = None if i == 9 else start_index + split_size
    part_data = data[start_index:end_index]
    print(f'part-{i} shape: {part_data.shape}')
    np.save(f'hadoop/tokenized_redpajama/stackexchange/part-0000{i}.npy', part_data)
```
