### ISSUE TITLE
FileNotFoundError: No such file or directory:"save_hf_to_composer"

### ISSUE THREAD

**Issue by sunzhe09** [princeton-nlp/LLM-Shearing#16]
something about save_hf_to_composer maybe missing?

**Comment by xiamengzhou** [comment]
Hi! This is an error in the README. You can call 

`python3 -m llmshearing.utils.composer_to_hf $HF_MODEL_NAME $OUTPUT_PATH`

to convert the model weights without adding `save_hf_to_composer `.
