### ISSUE TITLE
Use without flash-attn?

### ISSUE THREAD

**Issue by fakerybakery** [princeton-nlp/LLM-Shearing#17]
Can I use this without Flash Attention? I really want to do this on my M1 MacBook or AMD GPU. Thanks!

**Comment by xiamengzhou** [comment]
Hi using `model.attn_impl=normal` should deactivate flash attention!

**Comment by fakerybakery** [comment]
Thank you @xiamengzhou! Do you know how much slower it would be?

**Comment by xiamengzhou** [comment]
We didn't benchmark the normal attention, but generally it should be at least 20% slower without FA.
