### ISSUE TITLE
How can I use it on multiple nodes without slurm?

### ISSUE THREAD

**Issue by wang99711123** [princeton-nlp/LLM-Shearing#18]
Thanks for the excellent work!

And I want to run the code on multiple nodes, but I don't have slurm. Is there any feasible solution that does not use slurm?

**Comment by xiamengzhou** [comment]
Hi if a scheduler system is not available, you can run the command below on each node to do distributed training:

node1:
`composer --world_size 16 --node_rank 0 --master_addr 0.0.0.0 --master_port 7501 train.py 1.3B.yaml`

node2:
`composer --world_size 16 --node_rank 1 --master_addr 0.0.0.0 --master_port 7501 train.py 1.3.yaml`

You will need to change the world_size to be the total number of GPUs and the master address of the program. You can also refer to the [composer setup](https://github.com/mosaicml/llm-foundry/blob/45113ebf4ef2ad3714c1a9b51d9cca79bcafb921/scripts/train/README.md?plain=1#L116) for more detaills.
