### ISSUE TITLE
Any updates on the code?

### ISSUE THREAD

**Issue by AlpinDale** [princeton-nlp/LLM-Shearing#2]
Would love to experiment with LLM shearing, is the progress on finalizing the code still ongoing?

**Comment by xiamengzhou** [comment]
Sorry for the delay! We will make sure to publicize it by the end of this week.

**Comment by Coriana** [comment]
Commenting here for when this drops so I can go all Mistral on its ...

**Comment by yehuitang** [comment]
Hello! Thanks for your wonderful work! Has the code been released?

**Comment by xiamengzhou** [comment]
Hi! We just released the codebase :) Thanks for your interest in the work!
