### ISSUE TITLE
Question about ComposerMosaicLlama.forward

### ISSUE THREAD

**Issue by hanlinxuy** [princeton-nlp/LLM-Shearing#20]
Hello guys, This is not an issue but my question. I am confused about the forward function in  ComposerMosaicLlama. Why the pruning parameters (parameters which  "_z") can be read from batch? I can not find which class is preparing for those. In my understanding, those pruning parameters should be all in l0_module?

```
 def forward(self, batch):
        input_ids = batch["input_ids"]
        key_padding_mask = batch["attention_mask"].bool() if "attention_mask" in batch else None
        pruned_steps = batch.get("pruned_steps", None)
        if pruned_steps is not None:
            pruned_steps = pruned_steps[0].item()
        zs = {key: batch[key] for key in batch if "_z" in key} # why those parameters coming from batch?
        model_output = self.model(
            input_ids=input_ids, key_padding_mask=key_padding_mask, pruned_steps=pruned_steps, **zs
        )
        return model_output
```

Thank you very much!

**Comment by hanlinxuy** [comment]
another question is here (https://github.com/princeton-nlp/LLM-Shearing/blob/main/llmshearing/models/composer_llama.py#L293C8-L305C87)
Does this mean that the pruning of the embedding layer(same as ln_f) is detached? To avoid double multiplication, sometimes you'll transfer zs through batching, and sometimes you'll just use l0_module?
```
        tok_emb = self.transformer.wte(input_ids)
        if "hidden_z" in zs:
            tok_emb = tok_emb.mul(zs["hidden_z"])
        
        x = tok_emb 
        
        attn_bias = None # only consider the flash attention case
        attention_mask = prepare_decoder_attention_mask((tok_emb.size(0), tok_emb.size(1)), tok_emb)
        
        l0_output = None
        if self.l0_module is not None:
            assert zs == {}, "zs should be empty when using L0Module"
            zs = self.l0_module(calculate_lagrangian=False, pruned_steps=pruned_steps)
```

**Comment by xiamengzhou** [comment]
Hi! During training, `zs` is output of the l0_module.forward [here](https://github.com/princeton-nlp/LLM-Shearing/blob/eded724ff3d9cd82da446cc64227c5de7b28a6c5/llmshearing/models/composer_llama.py#L305). The zs parameters are left in the forward function of the ComposerMosaicLlama class for testing purposes.

**Comment by xiamengzhou** [comment]
For the second question --  I realize that placing the multiplication between hidden_z and token_emb after row 305 would be more appropriate. However, the practical impact of this placement may be minimal, as the layernorm forward function is implemented to eliminate pruned dimensions.

**Comment by hanlinxuy** [comment]
@xiamengzhou thank you very much for clarification!
