### ISSUE TITLE
sample data generate name

### ISSUE THREAD

**Issue by sunzhe09** [princeton-nlp/LLM-Shearing#21]
HI,after run bash sample_all_domains.sh I can't get the dirs as you list,eg:sample1、sample2、eval_merge.my dirs is:
.
├── eval
│   ├── arxiv
│   │   ├── index.json
│   │   └── shard.00000.mds
│   ├── book
│   │   ├── index.json
│   │   └── shard.00000.mds
│   ├── c4-rp
│   │   ├── index.json
│   │   └── shard.00000.mds
│   ├── cc
│   │   ├── index.json
│   │   └── shard.00000.mds
│   ├── github
│   │   ├── index.json
│   │   └── shard.00000.mds
│   ├── stackexchange
│   │   ├── index.json
│   │   └── shard.00000.mds
│   └── wiki
│       ├── index.json
│       └── shard.00000.mds
├── for_ft
│   ├── arxiv
│   │   ├── index.json
│   │   └── shard.00000.mds
│   ├── book
│   │   ├── index.json
│   │   └── shard.00000.mds
│   ├── c4-rp
│   │   ├── index.json
│   │   └── shard.00000.mds
│   ├── cc
│   │   └── index.json
│   ├── github
│   │   ├── index.json
│   │   └── shard.00000.mds
│   ├── stackexchange
│   │   ├── index.json
│   │   └── shard.00000.mds
│   └── wiki
│       ├── index.json
│       └── shard.00000.mds
└── for_prune
    ├── arxiv
    │   ├── index.json
    │   └── shard.00000.mds
    ├── book
    │   ├── index.json
    │   └── shard.00000.mds
    ├── c4-rp
    │   ├── index.json
    │   └── shard.00000.mds
    ├── cc
    │   ├── index.json
    │   └── shard.00000.mds
    ├── github
    │   ├── index.json
    │   └── shard.00000.mds
    ├── stackexchange
    │   ├── index.json
    │   └── shard.00000.mds
    └── wiki
        ├── index.json
        └── shard.00000.mds

**Comment by sunzhe09** [comment]
is there any mistake?

**Comment by hanlinxuy** [comment]
I think the example list is 
```
eval
| domain1
| domain2
| eval_merge
for_prune
| domain1
| domain2
for_ft
| domain1
| domain2
```
domain is like the "wiki, cc, c4-rp" as you shown.
for eval merge, you need to run 
```
python3 -m llmshearing.data.merge_data \
        --input_dir $INPUT_DIR \
        --output_dir $OUTPUT_DIR \
        --output_split eval_merge \
        --split_names domain1 domain2
```
to create it.

**Comment by sunzhe09** [comment]
what is INPUT_DIR like？is there any example? Maybe I should run eval\for_prune\for_ft one by one to get eval_merge dirs..

**Comment by hanlinxuy** [comment]
what I used is like
```
python3 -m llmshearing.data.merge_data  \
  --input_dir="${BASE}/LLM-Shearing/llmshearing/data/mds_sample_redpajama/eval/"  \
  --output_dir="${BASE}/LLM-Shearing/llmshearing/data/mds_sample_redpajama/eval" \
  --output_split eval_merge \
  --split_names arxiv  book  c4-rp  cc  github  stackexchange  wiki
```

**Comment by sunzhe09** [comment]
Thx ,I will have a try

**Comment by xiamengzhou** [comment]
Closing it now, feel free to reopen it if you encounter more issues!
