### ISSUE TITLE
How much compute will this take?

### ISSUE THREAD

**Issue by fakerybakery** [princeton-nlp/LLM-Shearing#22]
Hi,
If I want to make a 1B/3B model for Mistral, do you know approximately how many dollars I'll have to spend in compute, and whether I can do it on a consumer GPU? Thanks!

**Comment by xiamengzhou** [comment]
We use appriximately 1845 A100 GPU hours and 3310 A100 GPU hours to get the 1.3B and 2.7B model. However, the actual execution also heavily dependent on your set up and cluster speed.

**Comment by fakerybakery** [comment]
Hi, thanks for the info. So it cost ~$1000 for both (~$0.50/A100 GPU hour)?

**Comment by fakerybakery** [comment]
Also, are you planning to release a sheared Mistral version?

**Comment by xiamengzhou** [comment]
We use an in-house cluster at Princeton! I think A100 should be more expensive than $0.5 per hour though.

**Comment by xiamengzhou** [comment]
> Also, are you planning to release a sheared Mistral version?

We intend to add support for the mistral and pythia models in the upcoming weeks. We are in short of computes -- so I am not sure if we will end up delivering these models before the next stronger 7B model comes out.

**Comment by SinanAkkoyun** [comment]
Hi, when having full control over all finetuning data, does it make the most sense to first shear the base model and then finetune on top? Or is it better to finetune in advance (or a mixture of both)?

**Comment by SinanAkkoyun** [comment]
Alright, tysm!
