### ISSUE TITLE
Please share the alpaca generate and eval code and script to reproduce the results shared in 

### ISSUE THREAD

**Issue by sanyalsunny111** [princeton-nlp/LLM-Shearing#26]
Hey @xiamengzhou , great work. I am trying to reproduce your results. Could you please share the alpaca generation code and running scripts?

Thanks in advance.

**Comment by xiamengzhou** [comment]
Hi! We used SharedGPT to finetune the base models we released. Do you mean the generation protocol for SharedGPT?

**Comment by sanyalsunny111** [comment]
> Hi! We used SharedGPT to finetune the base models we released. Do you mean the generation protocol for SharedGPT?

yes generation protocol for shareGPT/alpaca eval.

**Comment by xiamengzhou** [comment]
Hi I just updated the code for instruction tuning in this folder:
https://github.com/princeton-nlp/LLM-Shearing/tree/main/instruction_tuning

Sorry that it's not very well documented, but I think it should be pretty straightforward!

**Comment by sanyalsunny111** [comment]
Very grateful for your help. Thank you again.
