### ISSUE TITLE
Docker Request

### ISSUE THREAD

**Issue by TonyZhanghm** [princeton-nlp/LLM-Shearing#28]
Hi! Would anyone be willing to share a docker image where they can run the code successfully? I've tried installing in different environments but keep getting errors from mosaic composer.

**Comment by xiamengzhou** [comment]
Hi! Unfortunately our system does not support docker building. Maybe you can check out the dockers supported by the composer team here? https://github.com/mosaicml/composer/blob/4dcbc2b47691cf6cd63c940a298a3b6e09a670c2/docker/README.md
