### ISSUE TITLE
Repeated assignment in l0_module.py

### ISSUE THREAD

**Issue by Longyichen** [princeton-nlp/LLM-Shearing#3]
In https://github.com/princeton-nlp/LLM-Shearing/blob/main/llmshearing/models/l0_module.py
````
def param_init_fn(self, module):
        """ Initialize the parameters for masking variables. """
        mean = math.log(1 - self.droprate_init) - math.log(self.droprate_init)
        mean = 5
        if isinstance(module, nn.Parameter):
            module.data.normal_(mean, 1e-2)
        else:
            for tensor in module.parameters():
                tensor.data.normal_(mean, 1e-2)
 
````

mean = math.log(1 - self.droprate_init) - math.log(self.droprate_init)
mean = 5

Repeated assignment, which may not be expected behavior
For what reason should this parameter be assigned to 5?

**Comment by xiamengzhou** [comment]
Hello! When the mean value is larger and positive, it indicates that the sampled initial 'z_loga' is more likely to be skewed toward a larger positive value. This, in turn, implies that the mask sampled from the hard concrete distribution tends to lean towards 1. This suggests that we get to preserve all the modules from the beginning of the pruning process. The initial mean assignment could be commented out.

**Comment by Longyichen** [comment]
thank u for ur kind and detail answers!
