### ISSUE TITLE
ShearedCodeLLama

### ISSUE THREAD

**Issue by SinanAkkoyun** [princeton-nlp/LLM-Shearing#35]
Hi! I am working on a copilot backend and, even though I am using a GPTQ quant of codellama7b, it is still eating lots of VRAM
DeepSeek coder seems to have severe issues understanding fill in the middle

I wanted to ask if you plan on also shearing CodeLlama? :)

**Comment by YanxiZSQ** [comment]
I also want to shearing codellama, do you success it?

**Comment by SinanAkkoyun** [comment]
@YanxiZSQ 
It would cost around 2k given this estimate https://github.com/princeton-nlp/LLM-Shearing/issues/22

**Comment by SinanAkkoyun** [comment]
I just fixed my deepseek prompt and I have to say they are very great models, closing!
