### ISSUE TITLE
Drive dress error

### ISSUE THREAD

**Issue by YanxiZSQ** [princeton-nlp/LLM-Shearing#39]
The Google Drive dress is error, I can not open it, would you give me a new dress, ths

![image](https://github.com/princeton-nlp/LLM-Shearing/assets/152595968/c75de3ba-009f-46ce-be00-7e6cd49653fe)

**Comment by xiamengzhou** [comment]
Sorry for the mistake! Could you try again? I just updated the link

**Comment by YanxiZSQ** [comment]
thx
