### ISSUE TITLE
Why update model parameters when training pruning parameters? 

### ISSUE THREAD

**Issue by KaihuaTang** [princeton-nlp/LLM-Shearing#4]
Thanks for your wonderful work!  I wonder why model parameters are updated together with the l0_module (pruning) parameters? Is it because training pruning models alone (freeze LLaMa parameters) are not as effective as the current implementation?

**Comment by xiamengzhou** [comment]
Hi! Yes, freezing the parameters doesn't yield performance as strong as updating them simultaneously, which aligns with our intuition.
