### ISSUE TITLE
Metric Scores and NQ Evaluation

### ISSUE THREAD

**Issue by Spico197** [princeton-nlp/LLM-Shearing#41]
Hi there, thanks very much for such an amazing work!
Currently, I'm trying to reproduce the results from the paper, but I have the following problems:

- Metric scores: lm-eval-harness would return acc and acc_norm at the same time. Do you have a preference to use one of them?
- NQ evaluation: I've checked the evaluation codebase and your starter scripts, but have no clues about the evaluation on the Natural Questions (NQ) dataset (it is not implemented in lm-eval-harness yet).
Did you write an evaluation script, or adopt an existing repo to get the scores?

Thank you so much for your time and response~

**Comment by xiamengzhou** [comment]
Hi! Sorry for the late reply:

I have update the script for evaluation `nq`, `boolq` and `gsm8k` here at [run_eval.sh](https://github.com/princeton-nlp/LLM-Shearing/blob/main/icl_eval/run_eval.sh). We use `nq_open` in the harness repo.

We also updated the metrics we use in [README.md](https://github.com/princeton-nlp/LLM-Shearing/blob/main/icl_eval/README.md) file.

Hope it helps and feel free to reach out again for any further questions!

**Comment by Spico197** [comment]
Thank you very much for the reply and the code update~
