### ISSUE TITLE
Release sheared model without re-training?

### ISSUE THREAD

**Issue by sbwww** [princeton-nlp/LLM-Shearing#44]
Hello, will you release sheared models without re-training? Currently, there are only some graphs showing the averaged ACC of each training checkpoint. I think it would be instructive if we can evaulate the un-trained model!

**Comment by xiamengzhou** [comment]
Do you mean the pruned models before training? Would love to release those if they are helpful. 
Stay tuned, I will get them uploaded within the week!

**Comment by sbwww** [comment]
Is there any update? Thanks in advance. @xiamengzhou

**Comment by xiamengzhou** [comment]
Apologies for the delay! You can find the two pruned models on HF now. 
[princeton-nlp/Sheared-LLaMA-1.3B-Pruned](https://huggingface.co/princeton-nlp/Sheared-LLaMA-1.3B-Pruned), [princeton-nlp/Sheared-LLaMA-2.7B-Pruned](https://huggingface.co/princeton-nlp/Sheared-LLaMA-2.7B-Pruned)

**Comment by sbwww** [comment]
Thank you very much!
