### ISSUE TITLE
duplicate mean values during mask initialization

### ISSUE THREAD

**Issue by czhang99** [princeton-nlp/LLM-Shearing#45]
Observed duplicated initializations when initializing the mean value for masking variables. Is one of them preferred over the other?

https://github.com/princeton-nlp/LLM-Shearing/blob/3560a877e2833c3da393923be0bd6753b6ef1c6d/llmshearing/models/l0_module.py#L45-L46C17

**Comment by xiamengzhou** [comment]
Hii! Check out here issue #3 for an details answer!

**Comment by czhang99** [comment]
well explained in https://github.com/princeton-nlp/LLM-Shearing/issues/3. closing the issue.
