### ISSUE TITLE
Pruning fine-tuned model

### ISSUE THREAD

**Issue by kiucho** [princeton-nlp/LLM-Shearing#55]
Thanks for sharing your great research.

I was wondering if pruning could be applied to an already fine-tuned model, so I'd like to ask for your advice. If so, would it be possible to have continued pre-training?

**Comment by xiamengzhou** [comment]
I think it should work for pruning fine-tuned models! The key is to add back the fine-tuning data at some point, either at the first stage (pruning) or second stage (continued pre-training).

**Comment by kiucho** [comment]
Thanks for reply! I'll try to make some progress.
