### ISSUE TITLE
Instruction tuning dataset

### ISSUE THREAD

**Issue by kiucho** [princeton-nlp/LLM-Shearing#57]
Thanks for sharing great research.

I'm trying to reproduce the result of instruction tuning(Sheared-LLaMA and Open-LLaMA both).
Can I get dataset which were used for tuning Sheared-LLaMA-ShareGPT? or weights for Open-LLaMA-ShareGPT.

Thanks.

**Comment by xiamengzhou** [comment]
Hi! The weights of Sheared-LLaMA-ShareGPT is provided on HF. [1.3b](https://huggingface.co/princeton-nlp/Sheared-LLaMA-1.3B-ShareGPT), [2.7b](https://huggingface.co/princeton-nlp/Sheared-LLaMA-2.7B-ShareGPT). 

Please find the datasets [here](https://drive.google.com/drive/folders/1Tvg3KAfQvIoeLfNNYrHRPGU1x90pqlrG) in the google drive.

**Comment by kiucho** [comment]
Thank you for your kind reply. I thought I had checked all the details of this project, but I guess I made a mistake, thanks again.
