### ISSUE TITLE
Can you provide script without using slurm or sbatch?

### ISSUE THREAD

**Issue by hanlinxuy** [princeton-nlp/LLM-Shearing#6]
I would like to do some experiments with llm-shearing but I do not have a cluster with SLURM. (I only have some GPUs). It would be nice if you guys can provide some scripts that can be used without sbatch.

**Comment by xiamengzhou** [comment]
Hi! I updated the scripts (`pruning.sh` and `continue_pretrain.sh`) to include commands to run the scripts directly. Essentially you only need to replace the sbatch head with `composer train.py`. Let me know if you need additional help.

**Comment by hanlinxuy** [comment]
> Hi! I updated the scripts (`pruning.sh` and `continue_pretrain.sh`) to include commands to run the scripts directly. Essentially you only need to replace the sbatch head with `composer train.py`. Let me know if you need additional help.

Thank you very much! I am going to test them!
