### ISSUE TITLE
The dtype of tokenized data should be uint32

### ISSUE THREAD

**Issue by ZhiYuanZeng** [princeton-nlp/LLM-Shearing#65]
In `tokenize_single_file.py` (line 61), the dtype of data saved in .npy file is set to be uint16. However it is not correct for the case where vocabulary size is large than 65535. It is more safe to set it to uint32, although it doubles the cost of storage.

<img width="1441" alt="image" src="https://github.com/princeton-nlp/LLM-Shearing/assets/50764547/4b841c28-d3cf-48d5-a5e9-c01a04351854">

**Comment by xiamengzhou** [comment]
Thanks for the suggestion! We worked with uint16 to save space for llama2, which only has a vocab of 32000, you are correct that we need to use uint32 for larger vocabs.
