### ISSUE TITLE
TypeError: load_data() missing 1 required positional argument: 'tokenizer_name' 

### ISSUE THREAD

**Issue by hanlinxuy** [princeton-nlp/LLM-Shearing#7]
Hello I was following the command in data/Readme.md

python3 -m llmshearing.data.merge_data \
        --input_dir $INPUT_DIR \
        --output_dir $OUTPUT_DIR \
        --output_split eval_merge \
        --split_names domain1 domain2

However I found two issues,
one is at line 31, you guys did not import sys, and the sys.argv[2:] should be change to sys.argv[1:], otherwise the input dir will always be none.
another is at line 50, It seems there should be a default value or guide for 'tokneizer_name'? Since I got TypeError: load_data() missing 1 required positional argument: 'tokenizer_name' 

Thank you very much in advance

**Comment by Longyichen** [comment]
i just remove tokneizer_name and it works

**Comment by hanlinxuy** [comment]
> i just remove tokneizer_name and it works

Thanks and Yeah I have also tried it. However it confused me... the class TextStreamingDataset doesnt need tokenizer_name

**Comment by xiamengzhou** [comment]
Code updated, thanks!
