### ISSUE TITLE
Open source the pruning mask.

### ISSUE THREAD

**Issue by Achazwl** [princeton-nlp/LLM-Shearing#70]
Can you please upload your pruning mask related to [Sheared-LLaMA-1.3B-Pruned](https://huggingface.co/princeton-nlp/Sheared-LLaMA-1.3B-Pruned) and [Sheared-LLaMA-2.7B-Pruned](https://huggingface.co/princeton-nlp/Sheared-LLaMA-2.7B-Pruned)?

This would help researchers conduct further analysis on weight importance, sparsity, etc.

**Comment by xiamengzhou** [comment]
Hi @Achazwl sorry for the late reply!

We uploaded masks [here](https://drive.google.com/drive/folders/1A_-88BqcOGa1Pbo-1ZShG2saU0cdRZgK), hope it helps!

**Comment by Achazwl** [comment]
Thanks a lot!
